#!/usr/bin/env python3
"""
Download Attachments with Parallel Processing

Downloads attachments from metadata files as they are generated by details_producer.py
Uses urllib with SSL bypass and works in parallel to avoid URL expiration issues.
"""

import json
import logging
import time
import os
from pathlib import Path
from typing import List, Dict, Any, Set
import urllib.request
import urllib.error
import ssl
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configuration
CONFIG = {
    'api_key': os.getenv('FRESHDESK_API_KEY'),
    'max_retries': 3,
    'retry_delay': 1,
    'delay_between_downloads': 0.1,  # Rate limiting
    'monitor_interval': 5,  # Check for new files every 5 seconds
    'max_wait_time': 300,  # Wait up to 5 minutes for new files
}

# Validate required environment variables
if not CONFIG['api_key']:
    raise ValueError("FRESHDESK_API_KEY environment variable is not set")

def setup_logging():
    """Setup logging"""
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s %(levelname)s [%(threadName)s] %(message)s',
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler('download_attachments_parallel.log', mode='a', encoding='utf-8')
        ],
        force=True,
    )

def sanitize_filename(filename: str) -> str:
    """Sanitize filename for filesystem safety"""
    invalid_chars = '<>:"/\\|?*'
    for char in invalid_chars:
        filename = filename.replace(char, '_')
    
    if len(filename) > 200:
        name, ext = filename.rsplit('.', 1) if '.' in filename else (filename, '')
        filename = name[:200-len(ext)-1] + '.' + ext if ext else name[:200]
    
    return filename

def download_file(url: str, filepath: str) -> bool:
    """Download a single file using urllib with SSL bypass"""
    for attempt in range(CONFIG['max_retries']):
        try:
            # Create SSL context that ignores certificate verification
            ssl_context = ssl.create_default_context()
            ssl_context.check_hostname = False
            ssl_context.verify_mode = ssl.CERT_NONE
            
            # Create opener with SSL context
            opener = urllib.request.build_opener(
                urllib.request.HTTPSHandler(context=ssl_context)
            )
            
            # For Freshdesk URLs, add authentication
            if 'freshdesk.com' in url:
                # Create password manager for authentication
                password_mgr = urllib.request.HTTPPasswordMgrWithDefaultRealm()
                password_mgr.add_password(None, url, CONFIG['api_key'], 'X')
                auth_handler = urllib.request.HTTPBasicAuthHandler(password_mgr)
                opener.add_handler(auth_handler)
            
            # Download the file using urlopen and read
            with opener.open(url) as response:
                with open(filepath, 'wb') as f:
                    f.write(response.read())
            
            return True
            
        except urllib.error.URLError as e:
            if "403" in str(e) or "Forbidden" in str(e):
                logging.warning(f"URL expired (403 Forbidden) on attempt {attempt + 1} for {url}")
                # Don't retry expired URLs
                return False
            else:
                logging.warning(f"URL Error on attempt {attempt + 1} for {url}: {e}")
                if attempt < CONFIG['max_retries'] - 1:
                    time.sleep(CONFIG['retry_delay'])
                    continue
                else:
                    logging.error(f"URL Error after {CONFIG['max_retries']} attempts: {e}")
                    return False
                
        except Exception as e:
            logging.warning(f"Error on attempt {attempt + 1} for {url}: {e}")
            if attempt < CONFIG['max_retries'] - 1:
                time.sleep(CONFIG['retry_delay'])
                continue
            else:
                logging.error(f"Error after {CONFIG['max_retries']} attempts: {e}")
                return False
    
    return False

def process_ticket_attachments(ticket_id: int, attachments_data: List[Dict[str, Any]]) -> int:
    """Process ticket-level attachments for a specific ticket"""
    if not attachments_data:
        return 0
    
    ticket_dir = Path('attachments') / str(ticket_id)
    ticket_dir.mkdir(parents=True, exist_ok=True)
    
    downloaded_count = 0
    
    for att in attachments_data:
        att_id = att.get('id')
        name = att.get('name')
        url = att.get('url') or att.get('attachment_url')
        
        if not (att_id and name and url):
            continue
        
        safe_name = sanitize_filename(str(name))
        dest = ticket_dir / safe_name
        
        if dest.exists():
            logging.info(f"File already exists: {dest}")
            downloaded_count += 1
            continue
        
        logging.info(f"Downloading ticket attachment: {name} for ticket {ticket_id}")
        
        if download_file(url, str(dest)):
            downloaded_count += 1
            logging.info(f"✅ Downloaded: {dest}")
        else:
            logging.error(f"❌ Failed to download: {name}")
        
        time.sleep(CONFIG['delay_between_downloads'])
    
    return downloaded_count

def process_conversation_attachments(ticket_id: int, attachments_data: List[Dict[str, Any]]) -> int:
    """Process conversation-level attachments for a specific ticket"""
    if not attachments_data:
        return 0
    
    ticket_dir = Path('conversation_attachments_downloads') / str(ticket_id)
    ticket_dir.mkdir(parents=True, exist_ok=True)
    
    downloaded_count = 0
    
    for att in attachments_data:
        att_id = att.get('id')
        name = att.get('name')
        url = att.get('url') or att.get('attachment_url')
        
        if not (att_id and name and url):
            continue
        
        safe_name = sanitize_filename(str(name))
        dest = ticket_dir / safe_name
        
        if dest.exists():
            logging.info(f"File already exists: {dest}")
            downloaded_count += 1
            continue
        
        logging.info(f"Downloading conversation attachment: {name} for ticket {ticket_id}")
        
        if download_file(url, str(dest)):
            downloaded_count += 1
            logging.info(f"✅ Downloaded: {dest}")
        else:
            logging.error(f"❌ Failed to download: {name}")
        
        time.sleep(CONFIG['delay_between_downloads'])
    
    return downloaded_count

def get_processed_files() -> Set[str]:
    """Get list of already processed metadata files"""
    processed_file = Path('processed_metadata_files.txt')
    if processed_file.exists():
        with open(processed_file, 'r') as f:
            return set(line.strip() for line in f if line.strip())
    return set()

def mark_file_processed(filename: str):
    """Mark a metadata file as processed"""
    processed_file = Path('processed_metadata_files.txt')
    with open(processed_file, 'a') as f:
        f.write(f"{filename}\n")

def monitor_and_download():
    """Monitor metadata directories and download attachments as they appear"""
    logging.info("🔍 Starting parallel monitoring and download process...")
    
    # Create output directories
    Path('attachments').mkdir(exist_ok=True)
    Path('conversation_attachments_downloads').mkdir(exist_ok=True)
    
    processed_files = get_processed_files()
    total_ticket_attachments = 0
    total_conversation_attachments = 0
    total_downloaded = 0
    
    start_time = time.time()
    
    while True:
        current_time = time.time()
        
        # Check if we should stop waiting
        if current_time - start_time > CONFIG['max_wait_time']:
            logging.info(f"⏰ Maximum wait time ({CONFIG['max_wait_time']}s) reached. Stopping monitoring.")
            break
        
        # Process ticket attachments
        ticket_attachments_dir = Path('ticket_attachments')
        if ticket_attachments_dir.exists():
            for att_file in ticket_attachments_dir.glob('ticket_*_attachments.json'):
                if str(att_file) not in processed_files:
                    try:
                        ticket_id = int(att_file.stem.split('_')[1])
                        data = json.loads(att_file.read_text(encoding='utf-8'))
                        
                        if isinstance(data, list) and data:
                            logging.info(f"📁 Processing new ticket attachments file: {att_file.name}")
                            downloaded = process_ticket_attachments(ticket_id, data)
                            total_downloaded += downloaded
                            total_ticket_attachments += len(data)
                            logging.info(f"Ticket {ticket_id}: {downloaded}/{len(data)} attachments downloaded")
                        
                        mark_file_processed(str(att_file))
                        
                    except Exception as e:
                        logging.error(f"Error processing {att_file}: {e}")
        
        # Process conversation attachments
        conversation_attachments_dir = Path('conversation_attachments')
        if conversation_attachments_dir.exists():
            for att_file in conversation_attachments_dir.glob('ticket_*_conversation_attachments.json'):
                if str(att_file) not in processed_files:
                    try:
                        ticket_id = int(att_file.stem.split('_')[1])
                        data = json.loads(att_file.read_text(encoding='utf-8'))
                        
                        if isinstance(data, list) and data:
                            logging.info(f"📁 Processing new conversation attachments file: {att_file.name}")
                            downloaded = process_conversation_attachments(ticket_id, data)
                            total_downloaded += downloaded
                            total_conversation_attachments += len(data)
                            logging.info(f"Ticket {ticket_id}: {downloaded}/{len(data)} conversation attachments downloaded")
                        
                        mark_file_processed(str(att_file))
                        
                    except Exception as e:
                        logging.error(f"Error processing {att_file}: {e}")
        
        # Check if details_producer.py is still running
        if not any('details_producer.py' in cmd for cmd in os.popen('ps aux').readlines()):
            logging.info("📊 Details producer has finished. Processing remaining files...")
            # Process any remaining files
            time.sleep(2)
            continue
        
        # Wait before next check
        logging.info(f"⏳ Waiting {CONFIG['monitor_interval']}s for new metadata files... (Processed: {len(processed_files)} files)")
        time.sleep(CONFIG['monitor_interval'])
    
    # Final summary
    logging.info("=" * 60)
    logging.info("📊 FINAL DOWNLOAD SUMMARY")
    logging.info("=" * 60)
    logging.info(f"Total ticket attachments found: {total_ticket_attachments}")
    logging.info(f"Total conversation attachments found: {total_conversation_attachments}")
    logging.info(f"Total attachments downloaded: {total_downloaded}")
    logging.info(f"Files saved to: attachments/ and conversation_attachments_downloads/")
    logging.info(f"Total metadata files processed: {len(processed_files)}")
    logging.info("=" * 60)
    
    return total_downloaded

def main():
    """Main function"""
    setup_logging()
    logging.info("🚀 Starting Parallel Download Attachments Script")
    logging.info("📋 This script works in parallel with details_producer.py")
    logging.info("🔍 Monitoring metadata directories for new files...")
    
    try:
        total_downloaded = monitor_and_download()
        logging.info(f"🎉 Download process completed! Total: {total_downloaded} attachments")
        return 0
    except KeyboardInterrupt:
        logging.info("🛑 Download process interrupted by user")
        return 1
    except Exception as e:
        logging.error(f"❌ Unexpected error: {e}")
        return 1

if __name__ == '__main__':
    raise SystemExit(main()) 